# Generated by Django 4.0.4 on 2022-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_brand_name_alter_category_name_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='holati',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
