# Generated by Django 4.0.4 on 2022-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_product_holati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mavjud',
        ),
        migrations.AddField(
            model_name='product',
            name='soni',
            field=models.IntegerField(null=True),
        ),
    ]
